services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastify-api-rest:
    build: ./neurosis-fastify-api-rest
    ports:
      - "3000:3000"
    volumes:
      - ./neurosis-fastify-api-rest:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/neurosis
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo

  vite:
    build: ./neurosis-vite
    ports:
      - "5173:5173"
    volumes:
      - ./neurosis-vite:/app
      - /app/node_modules
    environment:
      - VITE_API_REST=http://localhost:3000/v1
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo_data:


