version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neurosis-fastify-api-rest:
    build: ./neurosis-fastify-api-rest
    ports:
      - "3000:3000"
    volumes:
      - ./neurosis-fastify-api-rest:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/neurosis
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
    networks:
      - default

  neurosis-vite:
    build: ./neurosis-vite
    ports:
      - "5173:5173"
    volumes:
      - ./neurosis-vite:/app
      - /app/node_modules
    environment:
      - VITE_API_REST=http://localhost:3000/v1

  neurosis-expo-app:
    build: ./neurosis-expo-app
    # ports:
      # - "19000:19000"
    ports:
      - "19000:19000" # Expo Metro Bundler
      - "19001:19001" # Expo Development Server
    volumes:
      - ./neurosis-expo-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - EXPO_API_REST=http://localhost:3000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway" # Para acceder a servicios en tu máquina anfitriona (ej. tu API Fastify)
    networks:
      - default
    # AÑADE ESTA LÍNEA para mantener el contenedor en ejecución
    command: tail -f /dev/null

# Agrega las redes (si no las tenías)
networks:
  default: 
  # Puedes omitir esta sección si no necesitas configuraciones específicas
    driver: bridge      

volumes:
  mongo_data:


